module.exports = {
      "OriginTrail": "OriginTrail is an open protocol developed by /Trace_Labs and powered by /TRAC that serves as a trusted Decentralized /Knowledge_Graph or data foundation in the AI era. While AI offers great potential, it also heightens the risk of misinformation. OriginTrail enhances information discoverability and verifies its source to combat this issue through /chatDKG.",
      "Trace_Labs": "Trace Labs is the for-profit core development team of /OriginTrail, driving the project's development and innovation, focusing on B2B solutions.",
      "Knowledge_Graph": "A knowledge graph is a structured way of representing knowledge in a graph format. It connects data items in a structured and semantically meaningful way. Knowledge graphs are used by big tech giants like Google, Apple, Amazon to derive value from user data. OriginTrail is building the world's first /Decentralized_Knowledge_Graph",
      "Decentralized_Knowledge_Graph": "OriginTrail's DKG is a unique approach combining Blockchain and /Knowledge_Graph technologies for data organization and validation. It allows for the creation of a new AI-ready commodity called /Knowledge_Assets, enabling trusted knowledge sharing and value creation.",
      "Knowledge_Assets": "A Knowledge Asset is a dynamic and innovative resource with a NFT-backed ownership, a verifiable state through blockchain proofs, a discoverable /Unique_Asset_Locator, an AI-grade data structure or /Asset_Graphs, and the ability to form valuable connections with other Knowledge Assets within the /Decentralized_Knowledge_Graph, aligning with the power of network effects as defined by /Metcalfes_Law.",
      "Metcalfes_Law": "Metcalfe's Law states that the value of a network is proportional to the square of the number of its users. It's used to explain the value of networks or network effects. Dr. Bob Metcalfe who invented the law is an active advisor of /OriginTrail.",
      "Unique_Asset_Locator": "a Unique Asset Locator (UAL) is introduced as a Web3 extension of the URI/URL scheme used in Web2. Unlike URLs that point to Web2 resources and are controlled by centralized authorities, UALs are Web3 native identifiers owned by their users. They link to assets through verifiable /Asset_Graphs, providing full control and ownership over the linked resources.",
      "Asset_Graphs": "/Knowledge_Assets have their own asset graph within the /Decentralized_Knowledge_Graph (DKG) and is associated with a non-fungible token (NFT). Asset graphs are natively represented following the W3C-standardized /Resource_Description_Framework (RDF). This standard ensures compatibility with existing Knowledge Graphs like Google and semantic technologies such as JSON-LD, /SPARQL, OWL, and SHACL.",
      "SPARQL": "A query language and protocol used to query /Resource_Description_Framework (RDF) datasets.",
      "Resource_Description_Framework": "A standard model for data interchange on the Web, allowing for representation of information in a graph format. /Asset_Graphs uses RDF to present structured AI-ready data within /Knowledge_Assets.",
      "Nodes": "/OriginTrail Nodes require 50,000 TRAC to run and is open to any willing participants. The latest OriginTrail V6 Nodes are operational on the /OriginTrail_Parachain and will soon be available on other chains. OT Nodes commit to storing published /Knowledge_assets and help maintain the infrastructure of OriginTrail's /Decentralized_Knowledge_Graph.",
      "OriginTrail_Parachain": "OriginTrail's parachain in the Polkadot ecosystem tailored to the /Decentralized_Knowledge_Graph. It is powered by the /OTP token.",
      "OTP": "OTP has a max supply of 1 Billion and is inflationary. It serves as the gas and governance token for the /OriginTrail_Parachain.",
      "TRAC": "TRAC, an ERC-20 token, is essential for all operations on the DKG. It is an utility token with great driving the entire network, used for various operations including publishing /Knowledge_Assets and running /Nodes. It has a non-inflationary supply of 500M, all distributed during ICO in 2018.",
      "chatDKG": "chatDKG is an open-source framework promoting the adoption of trusted knowledge with AI, addressing AI hallucinations and misinformation by using verifiable /Knowledge_Assets. Find out more at chatdkg.ai!"
  };
