module.exports = {
    'otnoderestart': 'Restart the otnode service',
    'otnodestop': 'Stop the otnode service',
    'otnodestart': 'Start the otnode service',
    'otnodelogs': 'Show the last 100 entries of the otnode service logs',
    'otnoderestart2': 'Restart the otnode2 service',
    'otnodestop2': 'Stop the otnode2 service',
    'otnodestart2': 'Start the otnode2 service',
    'otnodelogs2': 'Show the last 100 entries of the otnode2 service logs',
    'othubbotrestart': 'Restart the othub-bot service',
    'othubbotstop': 'Stop the othub-bot service',
    'othubbotstart': 'Start the othub-bot service',
    'othubbotlogs': 'Show the last 100 entries of the othub-bot service logs',
    'otpsyncrestart': 'Restart the otp-sync service',
    'otpsyncstop': 'Stop the otp-sync service',
    'otpsyncstart': 'Start the otp-sync service',
    'otpsynclogs': 'Show the last 100 entries of the otp-sync service logs',
    'otpsync2restart': 'Restart the otp-sync2 service',
    'otpsync2stop': 'Stop the otp-sync2 service',
    'otpsync2start': 'Start the otp-sync2 service',
    'otpsync2logs': 'Show the last 100 entries of the otp-sync2 service logs',
    'otnodeapirestart': 'Restart the otnode-api service',
    'otnodeapistop': 'Stop the otnode-api service',
    'otnodeapistart': 'Start the otnode-api service',
    'otnodeapilogs': 'Show the last 100 entries of the otnode-api service logs',
    'otnodeapprestart': 'Restart the otnode-app service',
    'otnodeappstop': 'Stop the otnode-app service',
    'otnodeappstart': 'Start the otnode-app service',
    'otnodeapplogs': 'Show the last 100 entries of the otnode-app service logs',
  };
  